wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704830173.644725
    t:
      1:
      - 1
      - 11
      - 40
      - 41
      - 49
      - 51
      - 55
      - 105
      2:
      - 1
      - 11
      - 40
      - 41
      - 49
      - 51
      - 55
      - 105
      3:
      - 13
      - 19
      - 23
      4: 3.10.12
      5: 0.16.1
      6: 4.35.0
      8:
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0001
